version: "3"
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - "./data/influxdb:/var/lib/influxdb"
    environment:
      INFLUXDB_DB: "playground"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "toto"
      INFLUXDB_USER: "toto"
      INFLUXDB_USER_PASSWORD: "toto"

  chronograf:
    image: chronograf
    ports:
      - "8888:8888"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
