version: "3"
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - "./data/influxdb:/var/lib/influxdb"
    environment:
      INFLUXDB_DB: "playground"
      INFLUXDB_HTTP_AUTH_ENABLED: "false"

  chronograf:
    image: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
